id: P010612
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:16:29.270355
source_metadata:
  id: bdr:W1KG14784
  title: དཔེ་རྒྱུན་དཀོན་པའི་བླ་མ་འགའི་རྣམ་ཐར་དང་གནས་རི་ངོ་སྤྲོད་མདོར་བསྡུས་གསེར་གྱི་མེ་ལོང་།
  author: ''
  volumes:
    afef7475379b46889680180663522678:
      image_group_id: I1KG14883
      title: ''
      volume_number: 1
      total_pages: 90
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
