id: opecha:P010612
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14784
  title: དཔེ་རྒྱུན་དཀོན་པའི་བླ་མ་འགའི་རྣམ་ཐར་དང་གནས་རི་ངོ་སྤྲོད་མདོར་བསྡུས་གསེར་གྱི་མེ་ལོང་།
  volume: ''
  author: ''
