id: I84DDDB0E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:15:43+00:00'
last_modified: '2022-06-08T16:14:33.604204+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14784
  title: དཔེ་རྒྱུན་དཀོན་པའི་བླ་མ་འགའི་རྣམ་ཐར་དང་གནས་རི་ངོ་སྤྲོད་མདོར་བསྡུས་གསེར་གྱི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3C39:
      image_group_id: I1KG14883
      title: ''
      total_pages: 90
      order: 1
      base_file: 3C39.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
