id: I84DDDB0E
legacy_id: P010612
ocr_import_info:
  bdrc_scan_id: W1KG14784
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T09:15:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T05:15:09.079159+00:00'
last_modified: 2022-08-27 13:15:22.525302
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG14784
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG14784
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔེ་རྒྱུན་དཀོན་པའི་བླ་མ་འགའི་རྣམ་ཐར་དང་གནས་རི་ངོ་སྤྲོད་མདོར་བསྡུས་གསེར་གྱི་མེ་ལོང་།
statistics:
  ocr_word_mean_confidence_index: 0.9615724103087887
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG14883:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14883
      total_pages: 90
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG14883.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9615724103087887
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
